In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [8]:
arr[1:5]
# not including 5

array([1, 2, 3, 4])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:6]
# everthing up to 6
# same as [0:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]
# grab everthing starts with index 5

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
arr[0:5]=100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]
# a coloumn means grab everthing 

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:]=99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr
# will be changed as well
# the change made on original araay
# reference of original array, not a copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
# made a copy
arr_copy = arr.copy()

In [26]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy[:6]=100

In [28]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
# matrix

In [36]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
# two sets of brackets required or error.

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
# select number 5
arr_2d[0][0]

5

In [44]:
# select number 5
# same as above
arr_2d[0,0]

5

In [42]:
arr_2d[1][1]
# number 25

25

In [45]:
arr_2d[1,1]

25

In [47]:
# grab right up corner

arr_2d[:2,1:]

# up to row 2, coloumn starts from 1

array([[10, 15],
       [25, 30]])

In [48]:
# conditional selection

In [55]:
arr = np.arange(1,11)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr >5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [58]:
bool_arr = arr > 5

In [59]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [60]:
# do a conditional selection, pass boolean array into brakets, and will only get the results where this boolean array happens 
# to be true.

arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [61]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [64]:
arr_2d = np.arange(50).reshape(5,10)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
# grab 13,14,23,24

arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])