In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
#Two Demensional 

In [9]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_mat)
#the result has two sets of brackets, indicates this is a two demensional array, has three rows and three columns.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#create arrays by numpy's built in generation methods
np.arange(0,10)
#starts from zero, up to but not including 10
#takes integers out from a start and stop and given step size

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)
#add step size

array([0, 2, 4, 6, 8])

In [16]:
#generate araays of all zeros
np.zeros(3)

array([ 0.,  0.,  0.])

In [19]:
#pass a tuple of the demension you want
np.zeros((5,4))
#first represent rows, second represent coloumns

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [21]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [23]:
#linspace returns evenly spaced numbers over a specified internvel
#third arguments as number of points you want
np.linspace(0,5,10)
#want to get 10 evenly spaced points between 0 to 5
#one dimensional, because one set of brackets. two dimension, two sets of brackets. three dimension, three brackets.


array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [24]:
# create indentity matrix using numpy
np.eye(4)
#number of rows same as number of columns, and you have a diagonal of ones and everything esle is zero.

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [27]:
#create random of numbers
# np.random. press tab, you can see a lot of methods
# most common one:
np.random.rand(5)
#distributed from zero to one.

array([ 0.63089297,  0.14638003,  0.27469715,  0.59855425,  0.68170669])

In [28]:
np.random.rand(5,5)

array([[ 0.6798754 ,  0.65569681,  0.78217218,  0.35468133,  0.14373671],
       [ 0.14437536,  0.33707992,  0.39462887,  0.82301985,  0.59521998],
       [ 0.38164787,  0.80982378,  0.5380856 ,  0.07190545,  0.75642048],
       [ 0.16843901,  0.57527606,  0.62442   ,  0.15432482,  0.02941526],
       [ 0.83712747,  0.56274333,  0.92889347,  0.61981436,  0.43653167]])

In [30]:
# return a sample or many samples from the standard normal distribution 
np.random.randn(2)
#returns numbers not from a uniform distribution from zero to one, but instead from a standard normal distribution center around zero.

array([ 0.60364972, -0.49146542])

In [31]:
np.random.randn(2,2)

array([[ 1.91135493,  0.25137724],
       [ 0.25158755, -0.66215838]])

In [37]:
# return radom integers from low to high number
np.random.randint(1,100)
#just get one integer

67

In [38]:
np.random.randint(0,100,10)

array([71, 22, 19, 27, 81,  1,  5, 92,  4, 95])

In [39]:
# useful atributes and methods

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10)

In [43]:
ranarr

array([35, 42, 26, 24, 25, 34, 27, 10,  2, 17])

In [46]:
#reshape method, return same data in new shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.max()
#find the max value of that array

42

In [48]:
ranarr.min()

2

In [49]:
ranarr

array([35, 42, 26, 24, 25, 34, 27, 10,  2, 17])

In [51]:
# find out the max value's location

ranarr.argmax()

1

In [52]:
# min value's location
ranarr.argmin()

8

In [55]:
# figure out shape
arr.shape
#不加括号
# 25, means one dimensional 

(25L,)

In [56]:
arr = arr.reshape(5,5)

In [57]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape

(5L, 5L)

In [59]:
# data type
arr.dtype
#32 bit integers

dtype('int32')

In [61]:
#另一种方法
from numpy.random import randint

In [62]:
randint(0,100,5)

array([43, 27, 47, 14, 17])